apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:jittuki/Karmada-project.git'
    targetRevision: main
    path: 'workloads'  # Deployment YAML이 있는 폴더
  destination:
    server: 'https://192.168.40.122:32443'  # Karmada API 서버
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
