apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karmada-propagation
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: propagation-policies
          - path: workloads
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:jittuki/Karmada-project.git'
        targetRevision: main
        path: 'karmada-propagation/{{path}}'   # 여기서 repo 루트 기준 path를 지정
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
