#appset-karmada.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karmada-propagation
  namespace: argocd
spec:
  generators:
    - clusters: {}  
  template:
    metadata:
      name: '{{cluster.name}}-karmada-propagation'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:jittuki/Karmada-project.git'
        targetRevision: main
        path: karmada-propagation
        directory:
          recurse: true
      destination:
        server: '{{cluster.server}}'  
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true


