# propagation-all-cluster.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-all-cluster
  namespace: default
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
  placement:
    clusterAffinity:
      clusterNames:
      - jisu-member-1
      - jisu-member-2
  conflictResolution: Abort
  priority: 0
  schedulerName: karmada-scheduler
